### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by PierreOucif** [Barbicane-fr/maston#3]

**Comment by od-hunter** [comment]
Hello @PierreOucif Can you please provide more description to this? Please when you do can I be assigned?

**Comment by PierreOucif** [comment]
Sorry for the spam @od-hunter ...........

**Comment by od-hunter** [comment]
Sorry am I assigned or unassigned? Is this issue closed or open?

**Comment by PierreOucif** [comment]
@od-hunter it was an issue to test the assignment feature on Onlydust, so forget about it and I'm very sorry again for the spam ...

**Comment by od-hunter** [comment]
No problem
